myboard/api/urls.py
from django.urls import path
from api import views

app_name = "api"

urlpatterns = [
        #도서목록 http://127.0.0.0:8000/api/v1/books/1
        path('v1/books/', views.book_list, name='book_list'),
]

myboard/cms/urls.py
from django.urls import path
#from django.conf.urls import url

#from cms.views import *  #클래스있을 때 참조 방법
from cms import views #메소드를 참조하는 방법

app_name = 'cms'

urlpatterns = [
    #book_list
    path('book/', views.book_list, name='book_list'),
    #book_add
    path('book/add/', views.book_edit, name='book_add'),
    #book_edit
    path('book/modify/<int:book_id>/', views.book_edit, name='book_modify'),
    #book_remove
    path('book/delete/<int:book_id>/', views.book_remove, name='book_remove'),

    #impression_list
    path('impression/<int:book_id>/', views.ImpressionList.as_view(), name='impression_list'),
    #book_add
    path('impression/add/<int:book_id>/', views.impression_edit, name='impression_add'),
    #book_edit
    path('impression/modify/<int:book_id>/<int:impression_id>/', views.impression_edit,
        name='impression_modify'),
    #book_remove
    path('impression/delete/<int:book_id>/<int:impression:id>/', views.impression_remove,
        name='impression_remove'),


]

myboard/myboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include('cms.urls')),
    path('api/', include('api.urls')),

]

myboard/api/models.py
from django.db import models

# Create your models here.

myboard/cms/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    name = models.CharField('도서명', max_length=100)
    publisher = models.CharField('출판사', max_length=100, blank=True)
    price = models.IntegerField('가격', blank=True, default=0)

    def __str__(self):
        return self.name


class Impression(models.Model):
    book = models.ForeignKey(Book, verbose_name='도서', related_name='impressions',
            on_delete=models.CASCADE)
    comment = models.TextField('감상평', blank=True)

    def __str__(self):
        return self.comment

myboard/cms/forms.py
from django.forms import ModelForm
from cms.models import Book, Impression

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ('name', 'publisher', 'price',)

class ImpressionForm(ModelForm):
    class Meta:
        model = Impression
        fields = ('comment',)

myboard/api/views.py
from cms.models import Book

import collections
import json

# Create your views here.
def book_list(request):
    books = []
    for book in Book.objects.all().order_by("id"):
        #get impression
        impressions = []
        for impression in book.impressions.all().order_by("id"):
            impression_dict = OrderedDict([
                ('id', impression.id),
                ('comment', impression.comment),
            ])
            impressions.append(impression_dict)



        book_dict = OrderedDict([
            ('id', book.id),
            ('name', book.name),
            ('publisher', book.publisher),
            ('price', book.price),
         ])
        books.append(book_dict)

    data = OrderedDict([('books', books)])
    return render_json_response(reqeust, data)
def render_json_response(reqeust, data, status=None):
    json_str = json.dumps(data, indent=2)
    callback = request.GET.get('callback')
    if not callback:
        callback = request.POST.get('callback')  #외부에서 들어올때
    if callbalck:
        json_str = "%s(%s)" % (callback, json_str)
        response = HttpResponse(json_str, content_type="application/javascript;charset=UTF-8", status=status)
    else:
        response = HttpResponse(json_str, content_type="application/json;charset=UTF-8", status=status)

myboard/cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from cms.models import Book, Impression
from cms.forms import BookForm, ImpressionForm
from django.views.generic.list import ListView

# Create your views here.
def book_list(request):
    books = Book.objects.all().order_by('id')
    
    context = {}
    context['books'] = books

    return render(request, 'cms/book_list.html', context)

def book_edit(request, book_id=None):
#    return HttpResponse('도서 수정')
    if book_id:             #edit
        book = get_object_or_404(Book, pk=book_id)
    else:                   #add
        book = Book()

    if request.method == 'POST': #POST
        #POST된 request 데이터를 가지고 Form 생성
        form = BookForm(request.POST, instance=book)
        #save()
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            return redirect( 'cms:book_list')
    
    else: #GET
        form = BookForm(instance=book) #book instance에서 Form생성
        return render(request, 'cms/book_edit.html', dict(form=form, book_id=book_id))

def book_remove(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return redirect('cms:book_list')


class ImpressionList(ListView):
    context_object_name = "impressions"
    template_name = "cms/impression_list.html"
    paginate_by = 2
    
    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book, pk=kwargs["book_id"])
        impressions = book.impressions.all().order_by("id")
        self.object_list = impressions

        context = self.get_context_data(object_list=self.object_list, book=book)
        return self.render_to_response(context)

def impression_edit(request, book_id, impression_id=None):
    book = get_object_or_404(Book, pk=book_id)
    if impression_id:
        impression =get_object_or_404(Impression, pk=impression_id)
    else:
        impression = Impression()

    if request.method == 'POST':
        form = ImpressionForm(request.POST, instance=impression)
        if form.is_valid():
            impression = form.save(commit=False)
            impression.book = book    #감상평 추가/수정에book_id 필요
            impression.save()
            return redirect('cms:impression_list', book_id=book_id)
    else:#GET
        form = ImpressionForm(instance=impression) #impression instance에서 Form생성
    return render(request, 'cms/impression_edit.html', dict(fomr=form, book_id=book_id, impression_id=impression_id))

def impression_remove(request, book_id, impression_id):
    impression = get_object_or_404(Impression, pk=impression_id)
    imprssion.delete()
    return redirect('cms/impression_list', book_id=book_id )

myboard/cms/templates/cms/base.html
{% load i18n static %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html>
<head>
<meta chrset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">   <!--bootstrap 사용하기 위한 옵션-->
<link rel="stylesheet" href="{% static 'cms/css/bootstrap.min.css' %}">

{% block extra_css %}{% endblock %}
<title>{% block title %}My Books{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block content %}
            {{ content }}
        {% endblock %}
    </div>
<script src="{% static 'cms/js/jquery-3.3.1.js' %}"></script>
<script src="{% static 'cms/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

myboard/cms/templates/cms/book_edit.html
{% extends "cms/base.html" %}
{% load bootstrap4 %}

{% block title %}도서 추가/수정{% endblock %}

{% block content %}
<h4 class="mt-4 mb-5 border-bottom">도서 추가/수정</h4>
 {% if book_id %}
     <form action="{% url 'cms:book_modify' book_id=book_id %}" method="post">
 {% else %}
     <form action="{% url 'cms:book_add' %}" method="post">
 {% endif %}
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}

        <div class="form-group row">
            <div class="offset-md-3 col-md-9">
                <button type="submit" class="btn btn-primary">전송</button>
            </div>
        </div>
    </form>
    <a href="{% url 'cms:book_list' book_id=book_id %}" class="btn btn-secondary btn-sm">돌아가기</a>
{% endblock %}

myboard/cms/templates/cms/book_list.html
{% extends "cms/base.html" %}
{% block title %}도서 목록{% endblock %}

{% block content %}
    <h4 class="mt-4 border-bottom">도서 목록</h4>
    <a href="{% url 'cms:book_add' %}" class="btn btn-primary btn-sm my-3">추가</a>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">도서명</th>
            <th scope="col">출판사</th>
            <th scope="col">가격</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
            <th scope="row">{{ book.id }}</th>
            <td>{{book.name}}</td>
            <td>{{book.publisher}}</td>
            <td>{{book.price}}</td>
            <td>
                <a href="{% url 'cms:book_modify' book_id=book.id %}" class="btn btn-outline-primary btn-sm">수정</a>
                <a href="{% url 'cms:book_remove' book_id=book.id %}" class="btn btn-outline-danger btn-sm">삭제</a>
                <a href="{% url 'cms:impression_list' book_id=book.id %}" class="btn btn-outline-info btn-sm">감상평</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

myboard/cms/templates/cms/impression_edit.html
{% extends "cms/base.html %"}
{% load bootstrap4 %}

{% block title %}감상평 추가/수정{% endblock %}

{% block content%}

    <h4 class="mt-4 mb-5 border-bottom">감상평 추가/수정</h4>
    {% if impression_id %}
        <form action="{% url 'cms:impression_modify' book_id=book_id impression_id=impression_id %}" method="post">
    {% else %}
        <form action="{% url 'cms:impression_add' book_id=book_id %}" method="post">
    {% endif %}
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}

            <div class="form-group row">
                <div class="offset-md-3 col-md-9">
                    <button type="submit" class="btn btn-primary">전송</button>
                </div>
            </div>
        </form>
 
     <a href="{% url 'cms:impression_list' book_id=book_id %}" class="bn btn-secondary btn-sm">돌아가기</a>
{% endblock %}

myboard/cms/templates/cms/impression_list.html
{% extends "cms/base.html" %}

{% block title %}감상 목록{% endblock %}

{% block content %}
    <h4 class="mt-4 border-bottm">감상목록<small class="text-muted ml-3">{{ book.name }}</small>
</h4>
<a href="{% url 'cms:impression_add' book_id=book.id %}" class ="btn tn-primary btn-sm my-3">추가</a>
    
    <table class="table table-striped table-bordered">
      <thead>
          <th>ID</th>
          <th>Comment</th>
          <th>작업</th>
      </thead>
      <tbody>
        {% for impression in impressions %}
        <tr>
            <td>{{ impression.id }}</td>
            <td>{{ impression.comment | linebreaksbr }}</td>
            <td>
                <a href="{% url 'cms:impression_modify' book_id=book.id impression_id=impression.id %}" class="" btn btn-outline-primary btn-sm>수정</a>
                <button class="btn btn-outline-danger btn-sm del_confirm"
                        data-toggle = "modal"
                        data-target="#deleteModal"
                        data-url="{% url 'cms:impression_remove' book_id=book.id
                        impression_id=impression.id %}"
                        data-pk="{{ impression.id }}">삭제</button>
            </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <!-- To-Do(6) paginate -->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination">
        <!-- is exists previous page-->
        {% if page_obj.has.previous %} 
            <li class="page-i">       
        {% endif %}
        <!-- is exists current, etc page-->
        {% if page_obj.has_next %}
        {% endif %}
        <!-- is exists next page-->
      </ul>
    </nav>
    {% endif %}

    <a href="{% url 'cms:book_list'%}" class="btn btn-secondary btn-sm">돌아가기</a>

    <!-- To-Do(8) a -->
    
    {# 삭제를 확인하는 Modal Dialog #}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">확인</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <p>ID: [<span id="del_pk"></span>]를 삭제할까요?</p>
          </div>
          <div class="modal-footer">
            <a href="#" class="btn btn-primary" id="del_url">OK</a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block extra_js %}
<script>
$(function)(){
    $(".del_confirm").on("click", function(){
        $('#del_pk').text($(this)).data("pk");
        $('#del_pk').attr('href', '$(this).data("url")');
    });
});
</script>
{% endblock %}